# Generated by Django 5.2.5 on 2025-09-16 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0002_clienttranslation_is_liked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_translation', models.TextField()),
                ('translated_from', models.TextField()),
                ('translated_to', models.TextField()),
                ('feedback', models.TextField()),
                ('context', models.TextField(null=True)),
                ('translation', models.ForeignKey(db_column='initial_translation', on_delete=django.db.models.deletion.CASCADE, related_name='translationfeedback', to='translations.clienttranslation')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='clienttranslation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
