# Generated by Django 5.2.5 on 2025-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttranslation',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienttranslation',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
