# Generated by Django 5.2.5 on 2025-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectcomment',
            old_name='comment',
            new_name='text',
        ),
    ]
