# Generated by Django 5.2.5 on 2025-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_rename_comment_connectcomment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectcomment',
            name='created_by',
        ),
    ]
