# Generated by Django 5.2.5 on 2025-10-22 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_remove_connectcomment_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_comments', to=settings.AUTH_USER_MODEL)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_comments', to='connect.connectpost')),
            ],
        ),
    ]
