# Generated by Django 5.2.5 on 2025-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpost',
            name='language',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='meaning',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='tone',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='usage',
            field=models.TextField(default='null'),
        ),
    ]
