# Generated by Django 5.2.5 on 2025-11-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_connectpost_language_connectpost_meaning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectpost',
            name='text',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='connectpost',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
