# Generated by Django 5.2.5 on 2025-09-09 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_preferred_source_language', models.CharField(default='en', max_length=10)),
                ('user_preferred_target_language', models.CharField(default='zu', max_length=10)),
                ('display_profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('subscription_status', models.CharField(default='free', max_length=20)),
                ('profile_visibility', models.CharField(default='private', max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='clientsettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
