# Generated by Django 5.2.5 on 2025-09-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientsettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsettings',
            old_name='display_profile_picture',
            new_name='profile_picture',
        ),
    ]
