# Generated by Django 5.2.5 on 2025-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsettings', '0002_rename_display_profile_picture_clientsettings_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
    ]
