# Generated by Django 5.2.5 on 2025-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='avatars/default_profile.png', null=True, upload_to='avatars/'),
        ),
    ]
