# Generated by Django 5.2.5 on 2025-10-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_user_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
    ]
