# Generated by Django 5.2.5 on 2025-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_user_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='avatars/default_profile.png', null=True, upload_to='avatars/'),
        ),
    ]
