# Generated by Django 5.2.5 on 2025-09-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='original_tranlation',
            new_name='original_translation',
        ),
    ]
