# Generated by Django 5.2.5 on 2025-09-20 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientsetting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientSettings',
            new_name='ClientSetting',
        ),
    ]
